# Fetching the latest node image on apline linux
FROM node:alpine AS builder

# Declaring env
ENV NODE_ENV production

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY ./package.json ./
RUN npm install

#install nodemon to provide hot-reloading functionality.
RUN npm install nodemon --save-dev


COPY ./client/package.json ./client/
COPY ./server/package.json ./server/
RUN cd server && npm install
RUN cd client && npm install
# Copying all the files in our project
COPY . .


# Building our application
RUN cd client && npm run build

# Fetching the latest nginx image
FROM nginx

# Copying built assets from builder
COPY --from=builder /app/client/build /usr/share/nginx/html

# Copying our nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf