name: Run Directly on Pages
 
on:
  push:
    branches: [ "master" ]
    paths-ignore: 
      - "README.md"



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Install dependencies
      run: |
        npm install
        cd client && npm install
        cd ..
        cd server && npm install
        cd ..

    - name: Build app
      run: |
        cd server && node app.js
        cd ..
        cd client && npm run build
        cd ..
        

    - name: Deploy to GH Pages 🚀
      if: ${{ github.event_name != 'pull_request' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build