name: Docker Composer CI
 
on:
  push:
    branches: [ "master" ]



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: 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
          publish_dir: _site
      - uses: actions/checkout@v3
      - name: Build Task-Scheduler-App comp
        run: docker-compose up --build
